# Generated by Django 4.1.3 on 2022-12-13 04:11

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile')),
                ('is_zoho_active', models.IntegerField(default=0)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoho_branch_id', models.CharField(max_length=50, unique=True)),
                ('branch_name', models.CharField(blank=True, max_length=20, null=True)),
                ('branch_email', models.EmailField(max_length=30)),
                ('is_deleted', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='orderinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=400)),
                ('invoice_id', models.CharField(max_length=200)),
                ('customer_id', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('customer_name', models.CharField(max_length=200)),
                ('invoice_number', models.CharField(max_length=200)),
                ('invoice_total', models.CharField(max_length=200)),
                ('invoice_balance', models.CharField(max_length=200)),
                ('time_slot', models.CharField(max_length=200)),
                ('contactno', models.CharField(max_length=200)),
                ('location_coordinates', models.CharField(max_length=200)),
                ('location_url', models.CharField(max_length=400)),
                ('is_coordinate', models.BooleanField(default=0)),
                ('is_deleted', models.BooleanField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('zoho_updated_time', models.CharField(max_length=50)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='zohoaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.CharField(blank=True, max_length=100, unique=True)),
                ('clientsecret', models.CharField(max_length=200)),
                ('accesstoken', models.CharField(max_length=400)),
                ('refreshtoken', models.CharField(max_length=400)),
                ('redirecturi', models.CharField(max_length=400)),
                ('is_deleted', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='vehicleinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('vehiclename', models.CharField(max_length=200)),
                ('maxorders', models.CharField(max_length=400)),
                ('weightcapacity', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=400)),
                ('is_deleted', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_vehicle_not_available', models.BooleanField(default=0)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='slotinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slottime', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ordersdelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('location_coordinates', models.CharField(blank=True, max_length=250, null=True)),
                ('location_url', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.FloatField(default=0)),
                ('serialno', models.IntegerField(default=0)),
                ('shipping_address', models.CharField(blank=True, max_length=250, null=True)),
                ('collectedAmount', models.FloatField(default=0)),
                ('invoice_total', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=30, null=True)),
                ('upi', models.FloatField(default=0)),
                ('cash', models.FloatField(default=0)),
                ('other', models.FloatField(default=0)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('is_deleted', models.BooleanField(default=0)),
                ('is_published', models.BooleanField(default=0)),
                ('is_manually_assigned', models.BooleanField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('is_vehicle_update', models.BooleanField(default=0)),
                ('is_priority_change', models.BooleanField(default=0)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.orderinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vehicleinfo')),
            ],
        ),
        migrations.CreateModel(
            name='iteminfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoho_item_id', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('item_waight', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
