# Generated by Django 4.1.3 on 2023-01-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_quantity', models.IntegerField(default=0)),
                ('item_unit', models.IntegerField(default=0)),
                ('item_weight', models.FloatField(default=0)),
            ],
        ),
    ]
